Update tailored endpoint to work with a specific form
lblod/subsidy-applications-management-service pull request #5
Opened 2021-04-07 15:24 UTC by claire-lovisa

As we now extract tailored metadata for a specific form, the endpoint needed some updates. Here they are, could you have a look ? Thanks !

2021-04-07 16:21 UTC, HugaertsDries requested changes

2021-04-07 16:21 UTC, HugaertsDries commented on app.js
> +        const management = new SemanticFormManagement(configuration, meta);
what is the reason you create a new management service?

2021-04-07 16:21 UTC, HugaertsDries commented on lib/services/semantic-form-management.js
> +async function getSemanticFormsInStore(uuid, options) {
Usually instead of `options` I do `{sudo = false} = {}`. Then by default it is false and the code is a little more readable because:
1) See immediatly what the options can contain
2) Can just do `if(sudo){ console.log("sudo")}`

2021-04-07 16:38 UTC, claire-lovisa commented on app.js
> +        const management = new SemanticFormManagement(configuration, meta);
ah, didn't see it was defined already :sweat_smile:

2021-04-07 16:38 UTC, claire-lovisa commented on lib/services/semantic-form-management.js
> +async function getSemanticFormsInStore(uuid, options) {
good point !

2021-04-07 18:15 UTC, claire-lovisa commented
@HugaertsDries I pushed some fixes ! :)

2021-04-14 12:30 UTC, HugaertsDries commented
Any reason it hasn't been merged yet, should I take a look @claire-lovisa?

2021-04-14 13:10 UTC, claire-lovisa commented
@HugaertsDries I think I was just wating for your approval and then forgot about it haha

2021-04-14 13:54 UTC, HugaertsDries approved these changes

2021-04-14 13:55 UTC, merged